// Copyright (c) MASA Stack All rights reserved.
// Licensed under the Apache License. See LICENSE.txt in the project root for license information.

namespace Masa.Auth.ApiGateways.Caller;

public class TokenStateTemp
{
    public string Token { get; set; } = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjJDQUY0MTFEMTlENTUyQ0NDMDYxQzI0NkNDMUJBOUM2IiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2NjA1NDU3MjQsImV4cCI6MTY2MDU0OTMyNCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoxODIwMCIsImNsaWVudF9pZCI6Im1hc2Euc3RhY2sud2ViLWRldmVsb3BtZW50Iiwic3ViIjoiOWM5YTE3ZDYtMGIwZS00Njk3LTZiZDYtMDhkYTcwNjUwN2YwIiwiYXV0aF90aW1lIjoxNjYwNTQ1NzI0LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJBZG1pbmlzdHJhdG9yIiwidXNlck5hbWUiOiJhZG1pbiIsImVudmlyb25tZW50IjoiRGV2ZWxvcG1lbnQiLCJyb2xlIjoiW10iLCJzaWQiOiJGOThGNDIxOThCRkJCMTE1QzQzNzlCODhFQ0VEQTlCNyIsImlhdCI6MTY2MDU0NTcyNCwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSJdLCJhbXIiOlsicHdkIl19.XxUEsnxURX-5X0BFErPil0W3iuzPvFKpYW9naSIiOndDIqqAev1GdRvzwiR8ef72MQc824DxuI1qEktmSsOecUUdyUFCdGR6JiyTDMhNBpTcjxD8CBpKyOMtkaXbwZXQTLblzEgIotdoDqkIhAE0W6Ce5rIFCTsYNTtYg3A0b8LbYkJf65AwHFHS6zjuhYdLghP7qgzIVBmiiS8VRYQuLlFjYfikrxzVVQbEHZLtQf93TbIkPpaQvRsHaRzeiBAeYgLh0nKj7mNeU-FBfti5hWhEpSn-6lh_DykjJLV9107qnJH2XJsowb9rFDYf4oz2tRxcZ60g6IsOuSFfHZzsTA";
}
