// Copyright (c) MASA Stack All rights reserved.
// Licensed under the Apache License. See LICENSE.txt in the project root for license information.

namespace Masa.Auth.Contracts.Admin.Infrastructure.Enums;

public enum OperationTypes
{
    AddUser = 1,
    UpdateUser = 2,
    UpdateUserAuthorization = 3,
    RemoveUser = 4,
    UpdateUserPassword = 5,
    AddStaff = 6,
    UpdateStaff = 7,
    RemoveStaff = 8,
    SyncStaff = 9,
    UpdateStaffPassword = 10,
    AddRole = 11,
    UpdateRole = 12,
    RemoveRole = 13,
    AddPermission = 14,
    UpdatePermission = 15,
    RemovePermission = 16,
    AddTeam = 17,
    UpdateTeam = 18,
    RemoveTeam = 19,
    AddDepartment = 20,
    UpdateDepartment = 21,
    RemoveDepartment = 22,
    CopyDepartment = 23,
    AddClient = 24,
    UpdateClient = 25,
    RemoveClient = 26,
    AddUserClaim = 27,
    UpdateUserClaim = 28,
    RemoveUserClaim = 29,
    AddStandardUserClaims = 30,
    AddIdentityResource = 31,
    UpdateIdentityResource = 32,
    RemoveIdentityResource = 33,
    AddStandardIdentityResources = 34,
    AddApiScope = 35,
    UpdateApiScope = 36,
    RemoveApiScope = 37,
    AddApiResource = 38,
    UpdateApiResource = 39,
    RemoveApiResource = 40,
    AddCustomLogin = 41,
    UpdateCustomLogin = 42,
    RemoveCustomLogin = 43,
    Login = 44,
    SignOut = 45,
    AddThirdPartyIdp = 46,
    UpdateThirdPartyIdp = 47,
    RemoveThirdPartyIdp = 48,
}
