// Copyright (c) MASA Stack All rights reserved.
// Licensed under the Apache License. See LICENSE.txt in the project root for license information.

namespace Masa.Auth.Service.Admin.Infrastructure.Constants;

public static class UserFriendlyExceptionCodes
{
    public const string ROLE_NOT_EXIST = "RoleNotExist";
    public const string OPERATION_LOG_NOT_EXIST = "OperationLogNotExist";
    public const string API_RESOURCE_NOT_EXIST = "ApiResourceNotExist";
    public const string API_SCOPE_NOT_EXIST = "ApiScopeNotExist";
    public const string CUSTOM_LOGIN_NOT_EXIST = "CustomLoginNotExist";
    public const string IDENTITY_RESOURCE_NOT_EXIST = "IdentityResourceNotExist";
    public const string USER_CLAIM_NOT_EXIST = "UserClaimNotExist";
    public const string USER_NOT_EXIST = "UserNotExist";
    public const string INVALID_EMAIL_CAPTCHA = "InvalidEmailCaptcha";
    public const string INVALID_SMS_CAPTCHA = "InvalidSMSCaptcha";
    public const string CONNECT_ERROR = "ConnectError";
    public const string INVALID_SEND_EMAIL_TYPE = "InvalidSendEmailType";
    public const string INVALID_SEND_MSG_CODE_TYPE = "InvalidSendMsgCodeType";
    public const string INVALID_RESET_PASSWORD_TYPE = "InvalidResetPasswordType";
    public const string CAPTCHA_SENDED = "CaptchaSended";
    public const string STAFF_NOT_EXIST = "StaffNotExist";
    public const string TEAM_NOT_EXIST = "TeamNotExist";
    public const string TEAM_NAME_EXIST = "TeamNameExist";
    public const string DEPARTMENT_NOT_EXIST = "DepartmentNotExist";
    public const string PERMISSION_NOT_EXIST = "PermissionNotExist";
    public const string POSITION_NOT_EXIST = "PositionNotExist";
    public const string POSITION_NAMME_EXIST = "PositionNammeExist";
    public const string CLIENT_NOT_EXIST = "ClientNotExist";
    public const string CLIENT_ID_NOT_FOUND = "ClientIdNotFound";
    public const string INVALID_CAPTCHA = "InvalidCaptcha";
    public const string LDAP_ACCOUNT_NOTEXIST = "LdapAccountNotexist";
    public const string LDAP_ACCOUNT_VALIDATION_FAILED = "LdapAccountValidationFailed";
    public const string LDAP_NOT_CONFIGURED = "LdapNotConfigured";
    public const string ACCOUNT_DISABLED = "AccountDisabled";
    public const string ACCOUNT_NOT_EXIST = "AccountNotExist";
    public const string USER_PHONE_NUMBER_EXIST = "UserPhoneNumberExist";
    public const string USER_PHONE_NUMBER_NOT_EXIST = "UserPhoneNumberNotExist";
    public const string USER_EMAIL_EXIST = "UserEmailExist";
    public const string USER_EMAIL_NOT_EXIST = "UserEmailNotExist";
    public const string USER_ID_CARD_EXIST = "UserIdCardExist";
    public const string USER_ACCOUNT_EXIST = "UserAccountExist";
    public const string USER_ACCOUNT_PHONE_NUMBER_EXIST = "UserAccountPhoneNumberExist";
    public const string THIRD_PARTY_IDP_NOT_EXIST = "ThirdPartyIdpNotExist";
    public const string ADMINISTRATOR_DELETE_ERROR = "AdministratorDeleteError";
    public const string CURRENT_USER_DELETE_ERROR = "CurrentUserDeleteError";
    public const string LOGIN_FREEZE = "LoginFreeze";
    public const string DEPARTMENT_HAS_STAFF_DELETE = "DepartmentHasStaffDelete";
    public const string DEPARTMENT_ROOT_DELETE = "DepartmentRootDelete";
    public const string DAPARTMENT_NAME_EXIST = "DapartmentNameExist";
    public const string DAPARTMENT_NOT_FOUND = "DapartmentNotFound";
    public const string TEAM_HAS_STAFF_DELETE = "TeamHasStaffDelete";
    public const string PERMISSION_CODE_EXIST = "PermissionCodeExist";
    public const string PERMISSION_DELETE_ROLE_USED_ERROR = "PermissionDeleteRoleUsedError";
    public const string PERMISSION_DELETE_USER_USED_ERROR = "PermissionDeleteUserUsedError";
    public const string PERMISSION_DELETERELATION_ERROR = "PermissionDeleterelationError";
    public const string PERMISSION_API_BIND_ERROR = "PermissionApiBindError";
    public const string PERMISSION_API_PARENT_ERROR = "PermissionApiParentError";
    public const string PERMISSION_APP_ID_CODE_NOT_FOUND = "PermissionAppIdCodeNotFound";
    public const string PERMISSION_PARENT_ADD_ERROR = "PermissionParentAddError";
    public const string PERMISSIION_NOT_FOUND = "PermissiionNotFound";
    public const string PERMISSIION_NOT_API_TYPE = "PermissiionNotApiType";
    public const string PERMISSIION_API_TYPE = "PermissiionApiType";
    public const string CUSTOM_LOGIN_ENABLE_MULTIPLE = "CustomLoginEnableMultiple";
    public const string USER_NOT_FOUND = "UserNotFound";
    public const string USER_FROZEN = "UserFrozen";
    public const string STAFF_NOT_FOUND = "StaffNotFound";
    public const string PASSWORD_FAILED = "PasswordFailed";
    public const string INVALID_THIRD_PARTY_IDP_TYPE = "InvalidThirdPartyIdpType";
    public const string PHONE_NUMBER_AND_EMAIL_EMPTY_ERROR = "PhoneNumberAndEmailEmptyError";
    public const string EMAIL_SENDED = "EmailSended";
    public const string GUEST_ACCOUNT_OPERATE = "GuestAccountOperate";
    public const string DEMO_ENVIRONMENT_FORBIDDEN = "DemoEnvironmentForbidden";
    public const string FILE_READ_FAILED = "FileReadFailed";
    public const string THIRD_PARTY_IDP_NOT_FOUND = "ThirdPartyIdpNotFound";
    public const string THIRD_PARTY_USER_NOT_FOUND = "ThirdPartyUserNotFound";
    public const string THIRD_PARTY_USER_EXIST = "ThirdPartyUserExist";
    public const string ROLE_LIMIT_ERROR = "RoleLimitError";
    public const string IDENTITY_PROVIDER_NOT_FOUND = "IdentityProviderNotFound";
    public const string VALUE_IS_EMPTY = "ValueIsEmpty";
    public const string STAFF_EMAIL_EXIST = "StaffEmailExist";
    public const string STAFF_ID_CARD_EXIST = "StaffIdCardExist";
    public const string STAFF_JOB_NUMBER_EXIST = "StaffJobNumberExist";
    public const string STAFF_PHONE_NUMBER_EXIST = "StaffPhoneNumberExist";
    public const string THIRD_PARTY_IDP_NAME_EXIST = "ThirdPartyIdpNameExist";
    public const string ROLE_BIND_LIMIT_ERROR = "RoleBindLimitError";
}
